blog/urls.py
from django.conf.urls import url
from . import views


app_name='blog'
urlpatterns=[
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail')

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings


urlpatterns = [

    url(r'^', include('blog.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

lib/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.


class Question(models.Model):
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.utils import timezone

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post':post})

lib/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
# from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice
from django.views import generic
from django.utils import timezone

#
# # Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#
#     # template = loader.get_template('polls/index.html')
#     # context = {
#     #    'latest_question_list' : latest_question_list
#     # }
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
#     # return HttpResponse(template.render(context, request))
#
#
# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except:
#         raise Http404("Question does not exist")
#     return render(request, 'polls/detail.html', {'question': question})
#     # return HttpResponse('You are looking at question %s' % question_id)
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
#
#
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't selected a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Use HttpResponseRedirect to prevent from sending data 2 times
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

################################################################################

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        return  Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

blog/templates/blog/post_detail.html
{% extends 'lib/base.html' %}
{% block links %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
{% endblock %}
{% block container %}
    <div class="post">
        {% if post.published_date %}
            <p class="pub-date">Publication date - {{ post.published_date }}</p>
        {% endif %}
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p class="post-text">{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'lib/base.html' %}
{% block links %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
{% endblock %}
{% block container %}
    <h1 class="site-title">Boss' Blog</h1>
    <h2>Posts:</h2>
    {% for post in posts %}
        <div class="post">
            <p class="pub-date">Publication date - {{ post.published_date }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p class="post-text">{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

lib/templates/lib/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %}Boss' Site{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css"
          integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js"
            integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK"
            crossorigin="anonymous"></script>

    {% block links %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-light bg-faded">
    <ul class="nav navbar-nav">
        <li class="nav-item active">
            <a class="navbar-link" href="{% url 'blog:post_list' %}">Home Page</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'polls:index' %}">Polls</a>
        </li>
    </ul>

</nav>
<div class="container">
    {% block container %}
    {% endblock %}
</div>
</body>
</html>

polls/templates/polls/back.html
<a href="{% url 'blog:post_list' %}">Home Page</a>
<a href="{% url 'polls:index' %}">Polls</a>

polls/templates/polls/detail.html
{% extends 'lib/base.html' %}
{% block container %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} - {{ choice.votes }}</label>
    <br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'lib/base.html' %}
{% block links %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
{% endblock %}
{% block container %}
    {% if latest_question_list %}

        <ul class="list-group">
            {% for question in latest_question_list %}
                <li class="list-group-item col-sm-12">
                    <div class="row">
                        <div class="col-md-4 col-sm-6">
                            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                        </div>
                    </div>

                    <div class="row">
                        <p class="col-sm-3">{{ question.pub_date }}</p>
                        {% if question.was_published_recently %}
                            <p class="recent-publish col-sm-6">The question was published recently</p>
                        {% endif %}
                    </div>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'lib/base.html' %}
{% block container %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}